[package]
name = "tmc"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = { version = "0.18.3", features = ["rayon"] }
peroxide = { version = "0.40.0", features = ["parquet"] }
rayon = "1.11.0"
